class AuthError(Exception):
    pass

class CreatePaymentError(Exception):
    pass